import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

// These styles apply to every route in the application
import './globals.css';

import { validateEnv } from '@lib/env';
import Providers from '@src/providers';

const poppins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

if (process.env.NODE_ENV !== 'production') {
    validateEnv();
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={`${poppins.className} font-sans`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
