import type { Metadata } from 'next';
import { Poppins, Inter, Montserrat } from 'next/font/google';

// These styles apply to every route in the application
import './globals.css';

import { validateEnv } from '@lib/env';
import Providers from '@src/providers';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
});

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap',
    weight: ['400', '500', '600', '700'],
    variable: '--font-montserrat',
});

const poppins = Poppins({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

if (process.env.NODE_ENV !== 'production') {
    validateEnv();
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body
                className={`${poppins.variable} ${inter.variable} ${montserrat.variable} font-poppins`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
